FORMAT: 1A
HOST: http://api.themoviedb.org/3/

# The Movie Database API

This page has been deprecated. Please visit our new documentation located at **[https://developers.themoviedb.org/](https://developers.themoviedb.org/3)**.

If you're looking for help, please visit our [forums](https://www.themoviedb.org/talk). Thanks!